### ISSUE TITLE
Broken build because of dependency mismatch

### ISSUE THREAD

**Issue by alexanderscheible** [kamchatka-volcano/figcone#21]
Hi, 

first of all, thanks for the nice lib.

We have an issue building the lib.
There seems to be a problem with a dependency to sfun and SealLake. In the following [line](https://github.com/kamchatka-volcano/sfun/blob/2e8ee64725bcfea0661af77fe42ee26f7e6f29ac/CMakeLists.txt#L21) sfun requires SealLake_OptionalSubProjects which is not found by the used seal_lake. 

For the future, can you tag dependencies of figcone to specific commits/releases?

Unfortunately, we don't know when the error was introduced since we apparently used some cached version of the repo.

**Comment by kamchatka-volcano** [comment]
Hi, sorry for that(
I mistakenly set the git tag of the sfun library to the dev branch in release 3.0.0. Currently, I'm working on updating seal_lake and was rolling it out on the dev branches of my projects, so sfun got updated and has broken the build. It should be fixed now, as I restored the previous state of the dev branch. I won't be updating it later and I'm going to lock it for changes; it will remain in the repo for compatibility with figcone v3.0.0.

>can you tag dependencies of figcone to specific commits/releases?

Yes, I'm trying to. It was a stupid error. I'll consider making a pre-commit check that forbids using non-tag versions for dependencies on master branches of my projects.

**Comment by alexanderscheible** [comment]
Thanks for the quick response. 

Unfortunately, it is still not working. 
Error msg: 
![image (2)](https://github.com/kamchatka-volcano/figcone/assets/170917296/d21e491a-3ad0-4ad4-a730-23892f7242d9)

Before your fix, we had a working state by replacing the unknown "SealLake_OptionalSubProjects" by "SealLake_OptionalBuildSteps".

**Comment by alexanderscheible** [comment]
:+1:  It is working again. Thanks
